/**
 * ====================================================
 *  SEED SCRIPT — Pokémon Hunt
 * ====================================================
 *
 * Seeds the database with:
 *   • 100 Pokémon (real names + unique QR UUIDs)
 *   • 100 corresponding riddles (one per Pokémon)
 *   • 1 GameState singleton
 *
 * Run: node scripts/seed.js
 */

require('dotenv').config();

const fs = require('fs');
const path = require('path');
const mongoose = require('mongoose');
const { v4: uuidv4 } = require('uuid');
const Pokemon = require('../src/models/Pokemon');
const User = require('../src/models/User');

// Load QR mapping if it exists (generated by generateQR.js)
const mappingPath = path.join(__dirname, '..', 'qr-codes', 'qr-mapping.json');
let qrMapping = {};
if (fs.existsSync(mappingPath)) {
    qrMapping = JSON.parse(fs.readFileSync(mappingPath, 'utf-8'));
    console.log('📄 Loaded QR mapping from qr-codes/qr-mapping.json');
} else {
    console.log('⚠️  No qr-mapping.json found — generating random UUIDs (run generateQR.js first for physical QR sync)');
}
const Riddle = require('../src/models/Riddle');
const GameState = require('../src/models/GameState');

// ---------- 100 Pokémon with riddles ----------
const pokemonData = [
    { name: 'Bulbasaur', riddle: 'I carry a seed on my back that grows as I do. Who am I?' },
    { name: 'Ivysaur', riddle: 'My bud blooms as I gain experience in battle. Who am I?' },
    { name: 'Venusaur', riddle: 'A massive flower on my back absorbs sunlight. Who am I?' },
    { name: 'Charmander', riddle: 'My tail flame shows my life force. Who am I?' },
    { name: 'Charmeleon', riddle: 'I am fierce and my tail burns brighter when I rage. Who am I?' },
    { name: 'Charizard', riddle: 'I fly and breathe fire hot enough to melt boulders. Who am I?' },
    { name: 'Squirtle', riddle: 'I hide in my shell and spray water at foes. Who am I?' },
    { name: 'Wartortle', riddle: 'My furry tail helps me swim swiftly. Who am I?' },
    { name: 'Blastoise', riddle: 'Cannons on my shell blast water at incredible pressure. Who am I?' },
    { name: 'Caterpie', riddle: 'I am a tiny bug with a big appetite for leaves. Who am I?' },
    { name: 'Metapod', riddle: 'I harden my shell while I wait to transform. Who am I?' },
    { name: 'Butterfree', riddle: 'My wings scatter poisonous powder as I fly. Who am I?' },
    { name: 'Weedle', riddle: 'A sharp stinger on my head warns predators. Who am I?' },
    { name: 'Kakuna', riddle: 'I barely move but inside I am evolving rapidly. Who am I?' },
    { name: 'Beedrill', riddle: 'I attack in swarms with large poisonous stingers. Who am I?' },
    { name: 'Pidgey', riddle: 'A common bird found near forests and fields. Who am I?' },
    { name: 'Pidgeotto', riddle: 'I patrol a wide territory and hunt prey from the sky. Who am I?' },
    { name: 'Pidgeot', riddle: 'I fly at Mach 2 and have a gorgeous plume. Who am I?' },
    { name: 'Rattata', riddle: 'I gnaw on anything with my sharp front teeth. Who am I?' },
    { name: 'Raticate', riddle: 'My whiskers help me balance and I can chew through steel. Who am I?' },
    { name: 'Spearow', riddle: 'I am small but fierce and cry with a loud voice. Who am I?' },
    { name: 'Fearow', riddle: 'My long beak is perfect for catching prey in the ground. Who am I?' },
    { name: 'Ekans', riddle: 'Read my name backwards and you will know what I am. Who am I?' },
    { name: 'Arbok', riddle: 'The pattern on my hood intimidates enemies. Who am I?' },
    { name: 'Pikachu', riddle: 'I store electricity in my red cheek pouches. Who am I?' },
    { name: 'Raichu', riddle: 'I evolved from the world\'s most famous electric mouse. Who am I?' },
    { name: 'Sandshrew', riddle: 'I curl into a ball to protect myself in the desert. Who am I?' },
    { name: 'Sandslash', riddle: 'My claws are perfect for digging and my back is full of spikes. Who am I?' },
    { name: 'Nidoran♀', riddle: 'I am a small poison-type with a gentle nature. Who am I?' },
    { name: 'Nidorina', riddle: 'I protect my young fiercely with my horn. Who am I?' },
    { name: 'Nidoqueen', riddle: 'I am a powerful queen who shields my colony. Who am I?' },
    { name: 'Nidoran♂', riddle: 'I am small with a large ear and a poison horn. Who am I?' },
    { name: 'Nidorino', riddle: 'I charge at enemies with my hardened horn. Who am I?' },
    { name: 'Nidoking', riddle: 'I am a king with a powerful tail that can topple towers. Who am I?' },
    { name: 'Clefairy', riddle: 'I dance under the full moon in groups. Who am I?' },
    { name: 'Clefable', riddle: 'I am rarely seen and said to bring happiness. Who am I?' },
    { name: 'Vulpix', riddle: 'I have six curly tails and breathe small flames. Who am I?' },
    { name: 'Ninetales', riddle: 'My nine tails each contain a different mystical power. Who am I?' },
    { name: 'Jigglypuff', riddle: 'My song puts everyone to sleep. Who am I?' },
    { name: 'Wigglytuff', riddle: 'My body is so soft that I bounce when I fall. Who am I?' },
    { name: 'Zubat', riddle: 'I navigate dark caves using ultrasonic waves. Who am I?' },
    { name: 'Golbat', riddle: 'I drink blood and fly silently through the night. Who am I?' },
    { name: 'Oddish', riddle: 'I look like a plant and walk around at night. Who am I?' },
    { name: 'Gloom', riddle: 'My drool smells terrible but attracts certain prey. Who am I?' },
    { name: 'Vileplume', riddle: 'I have the largest petals in the world that release toxic pollen. Who am I?' },
    { name: 'Paras', riddle: 'Mushrooms on my back control my movements. Who am I?' },
    { name: 'Parasect', riddle: 'The mushroom on my back has taken over my body completely. Who am I?' },
    { name: 'Venonat', riddle: 'My big eyes act as radar in the darkness. Who am I?' },
    { name: 'Venomoth', riddle: 'I scatter poisonous scales when I flap my wings. Who am I?' },
    { name: 'Diglett', riddle: 'I pop out of the ground but nobody knows what is below. Who am I?' },
    { name: 'Dugtrio', riddle: 'Three of us share one body underground. Who am I?' },
    { name: 'Meowth', riddle: 'I love shiny coins and my charm brings luck. Who am I?' },
    { name: 'Persian', riddle: 'I am an elegant cat admired for my jeweled forehead. Who am I?' },
    { name: 'Psyduck', riddle: 'I always have a headache and unleash psychic power from it. Who am I?' },
    { name: 'Golduck', riddle: 'I am the fastest swimmer and possess psychic abilities. Who am I?' },
    { name: 'Mankey', riddle: 'I get angry at the slightest provocation. Who am I?' },
    { name: 'Primeape', riddle: 'I am always furious — even when I sleep. Who am I?' },
    { name: 'Growlithe', riddle: 'I am a loyal fire pup that guards its trainer. Who am I?' },
    { name: 'Arcanine', riddle: 'I run so gracefully that I am called the legendary Pokémon. Who am I?' },
    { name: 'Poliwag', riddle: 'The spiral on my belly is actually my intestines showing through. Who am I?' },
    { name: 'Poliwhirl', riddle: 'I can live on land and water and my spiral makes foes drowsy. Who am I?' },
    { name: 'Poliwrath', riddle: 'I am a powerful fighter that can swim entire oceans. Who am I?' },
    { name: 'Abra', riddle: 'I sleep 18 hours a day and teleport when in danger. Who am I?' },
    { name: 'Kadabra', riddle: 'I hold a spoon that amplifies my psychic power. Who am I?' },
    { name: 'Alakazam', riddle: 'My IQ is over 5000 and I hold two spoons. Who am I?' },
    { name: 'Machop', riddle: 'I train by lifting heavy rocks in the mountains. Who am I?' },
    { name: 'Machoke', riddle: 'I wear a belt to control my overwhelming strength. Who am I?' },
    { name: 'Machamp', riddle: 'I have four arms and can throw 500 punches per second. Who am I?' },
    { name: 'Bellsprout', riddle: 'I sway my thin body to catch unsuspecting bugs. Who am I?' },
    { name: 'Weepinbell', riddle: 'I use my hook to hang from trees and catch prey with acid. Who am I?' },
    { name: 'Victreebel', riddle: 'I lure prey with sweet honey then dissolve them. Who am I?' },
    { name: 'Tentacool', riddle: 'I drift in the ocean and sting anything I touch. Who am I?' },
    { name: 'Tentacruel', riddle: 'My 80 tentacles stretch out to trap prey. Who am I?' },
    { name: 'Geodude', riddle: 'I look like a rock and punch with my stone fists. Who am I?' },
    { name: 'Graveler', riddle: 'I roll down mountains and nothing can stop me. Who am I?' },
    { name: 'Golem', riddle: 'I shed my skin once a year by exploding. Who am I?' },
    { name: 'Ponyta', riddle: 'My fiery mane grows hotter as I run faster. Who am I?' },
    { name: 'Rapidash', riddle: 'I gallop at 150 mph with a blazing mane. Who am I?' },
    { name: 'Slowpoke', riddle: 'I take 5 seconds to feel pain after being hit. Who am I?' },
    { name: 'Slowbro', riddle: 'A Shellder bit my tail and we became one. Who am I?' },
    { name: 'Magnemite', riddle: 'I float using electromagnetic waves. Who am I?' },
    { name: 'Magneton', riddle: 'Three of me joined together create powerful magnetic fields. Who am I?' },
    { name: 'Farfetchd', riddle: 'I always carry a leek stalk and I am very rare. Who am I?' },
    { name: 'Doduo', riddle: 'My two heads think differently but run together. Who am I?' },
    { name: 'Dodrio', riddle: 'My three heads represent joy, sorrow, and anger. Who am I?' },
    { name: 'Seel', riddle: 'I clap my fins and love swimming in icy water. Who am I?' },
    { name: 'Dewgong', riddle: 'I sleep on icy ocean beds and my body is pure white. Who am I?' },
    { name: 'Grimer', riddle: 'I was born from polluted sludge and leave a toxic trail. Who am I?' },
    { name: 'Muk', riddle: 'I am so toxic that grass dies wherever I walk. Who am I?' },
    { name: 'Shellder', riddle: 'My shell is harder than diamond and my tongue is always out. Who am I?' },
    { name: 'Cloyster', riddle: 'My spiky shell is impenetrable and I launch ice spikes. Who am I?' },
    { name: 'Gastly', riddle: 'I am made of gas and can envelop anyone to suffocate them. Who am I?' },
    { name: 'Haunter', riddle: 'I lick my foes with my ghostly tongue and they start shaking. Who am I?' },
    { name: 'Gengar', riddle: 'I hide in shadows and drop the room temperature by 10 degrees. Who am I?' },
    { name: 'Onix', riddle: 'I am a 30-foot rock snake that burrows underground. Who am I?' },
    { name: 'Drowzee', riddle: 'I eat dreams through the noses of sleeping people. Who am I?' },
    { name: 'Hypno', riddle: 'I swing my pendulum to put anyone into deep sleep. Who am I?' },
    { name: 'Krabby', riddle: 'I blow bubbles when I feel threatened on the beach. Who am I?' },
    { name: 'Kingler', riddle: 'My oversized claw has the crushing power of 10,000 psi. Who am I?' },
    { name: 'Voltorb', riddle: 'I look like a Poké Ball and I explode when startled. Who am I?' },
    { name: 'Electrode', riddle: 'I am known as the Bomb Ball and I am the fastest exploder. Who am I?' },
];

const seed = async () => {
    try {
        await mongoose.connect(process.env.MONGODB_URI);
        console.log('Connected to MongoDB for seeding...\n');

        // Clear existing data
        await Pokemon.deleteMany({});
        await Riddle.deleteMany({});
        await GameState.deleteMany({});
        await User.deleteMany({});
        console.log('Cleared existing Pokémon, Riddle, GameState, and User collections.');

        // Seed Pokémon and Riddles
        for (const data of pokemonData) {
            // Create the Pokémon first (without riddleId for now)
            const pokemon = await Pokemon.create({
                name: data.name,
                qrCodeValue: qrMapping[data.name] || uuidv4(),
                isCaught: false,
                caughtByTeamId: null,
                isQrActive: true,
            });

            // Create the corresponding riddle
            const riddle = await Riddle.create({
                question: data.riddle,
                answerPokemonId: pokemon._id,
                isActive: true,
            });

            // Link riddle back to Pokémon
            pokemon.riddleId = riddle._id;
            await pokemon.save();

            console.log(`  ✓ ${pokemon.name} — QR: ${pokemon.qrCodeValue}`);
        }

        // Create singleton GameState
        await GameState.create({
            isStarted: false,
            isEnded: false,
            maxDeckSize: 4,
        });
        console.log('\n✓ GameState singleton created (maxDeckSize: 4)');

        // Seed admin user
        const adminName = process.env.ADMIN_NAME || 'Admin';
        await User.create({
            name: adminName,
            role: 'admin',
            teamId: null,
        });
        console.log(`✓ Admin user created (name: "${adminName}")`);

        console.log(`\n🎉 Seeded ${pokemonData.length} Pokémon with riddles successfully!\n`);

        process.exit(0);
    } catch (error) {
        console.error('Seed error:', error);
        process.exit(1);
    }
};

seed();
